spring:
  datasource:
    mysql:
      username: root
      password: 1
      url: jdbc:mysql://mysqldb:3306/rest_api_library?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.jdbc.Driver
    postgres:
      username: adpostgresql
      password: 1
      url: jdbc:postgresql://postgresdb:5432/rest_library_ver2?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      driver-class-name: org.postgresql.Driver

elasticsearch:
  port: 9200
  host: elastic
mq:
  username: guest
  password: guest
  host: rabbitmq
  port: 15672
  worker:
    xchange: rabbit.worker
    queuename: worker.queue
    key: key.worker
  rpc:
    xchange: rabbit.rpc
    queuename: rpc.queue
    key: key.rpc
  ps:
    xchange: rabbit.ps
    queuename: ps.queue
    key: key.ps

redis:
  port: 6379
  host: redis-server