spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: khoadamtam29122022@gmail.com
    password: ucxbbabcdueexmpu
secret:
  key: khoa2001
  timer: 120000000
email:
  from: khoadamtam29122022@gmail.com
  to: khoadamtam@gmail.com
crawler:
  url: https://nhasachmienphi.com/
  content: body .content_p.content_p_al
  agent: Mozilla/5.0

