server:
  port: 8088
  message: Hello Spring Boot

spring:
  profiles:
    active: local, common
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

#logging:
#  file:
#    name: app.log
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#    file: "%d %p %c{1.} [%t] %m%n"

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log