server:
  port: 8088
  message: Hello Spring Boot

spring:
  profiles:
    active: local, common
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

logging:
  file:
    path: logs
